//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPlaneacionDocente.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatProyectos
    {
        public int id { get; set; }
        public string strNombre { get; set; }
        public string strDescripcion { get; set; }
        public Nullable<int> idCatMateria { get; set; }
        public Nullable<int> idCatBloque { get; set; }
        public Nullable<int> idCatGrado { get; set; }
        public Nullable<int> idCatPeriodo { get; set; }
        public Nullable<int> idPlaneacion { get; set; }
    
        public virtual TblPlaneacion TblPlaneacion { get; set; }
    }
}
