//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPlaneacionDocente.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlaneacionEntities : DbContext
    {
        public PlaneacionEntities()
            : base("name=PlaneacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatBloques> CatBloques { get; set; }
        public virtual DbSet<CatGrado> CatGrado { get; set; }
        public virtual DbSet<CatPeriodo> CatPeriodo { get; set; }
        public virtual DbSet<CatProyectos> CatProyectos { get; set; }
        public virtual DbSet<CatTipoUsuario> CatTipoUsuario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblPersonal> TblPersonal { get; set; }
        public virtual DbSet<TblTemas> TblTemas { get; set; }
        public virtual DbSet<TblUsuarios> TblUsuarios { get; set; }
        public virtual DbSet<CatCicloEscolar> CatCicloEscolar { get; set; }
        public virtual DbSet<CatGrupos> CatGrupos { get; set; }
        public virtual DbSet<TblActividadesEnseñanzaAprendizaje> TblActividadesEnseñanzaAprendizaje { get; set; }
        public virtual DbSet<TblAtributos> TblAtributos { get; set; }
        public virtual DbSet<TblEstrategiasIntervencion> TblEstrategiasIntervencion { get; set; }
        public virtual DbSet<TblEvidenciaAprendizaje> TblEvidenciaAprendizaje { get; set; }
        public virtual DbSet<TblInstrumentosEvaluacion> TblInstrumentosEvaluacion { get; set; }
        public virtual DbSet<TblMaterialRecursosDidacticos> TblMaterialRecursosDidacticos { get; set; }
        public virtual DbSet<TblObjetosAprendizaje> TblObjetosAprendizaje { get; set; }
        public virtual DbSet<TblPlanDeClase> TblPlanDeClase { get; set; }
        public virtual DbSet<TblTiempo> TblTiempo { get; set; }
        public virtual DbSet<CatMateria> CatMateria { get; set; }
        public virtual DbSet<TblPlaneacion> TblPlaneacion { get; set; }
    }
}
