//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPlaneacionDocente.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblAtributos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAtributos()
        {
            this.TblPlanDeClase = new HashSet<TblPlanDeClase>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        public string strApertura { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        public string strDesarrollo { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        public string strCierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPlanDeClase> TblPlanDeClase { get; set; }
    }
}
