//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPlaneacionDocente.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblPlanDeClase
    {
        public int id { get; set; }
        public Nullable<int> idActividadesEnseñanzaAprendizaje { get; set; }
        public Nullable<int> idTiempo { get; set; }
        public Nullable<int> idAtributos { get; set; }
        public Nullable<int> idEvidenciaAprendizaje { get; set; }
        public Nullable<int> idInstrumentosEvaluacion { get; set; }
        public Nullable<int> idEstrategiasIntervencion { get; set; }
        public Nullable<int> idMateriasRecursosDidacticos { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        public string strBibliografia { get; set; }
        [Required(ErrorMessage = "Este Campo es Requerido")]
        public string strObservaciones { get; set; }
        public Nullable<int> idPlaneacion { get; set; }
    
        public virtual TblActividadesEnseñanzaAprendizaje TblActividadesEnseñanzaAprendizaje { get; set; }
        public virtual TblAtributos TblAtributos { get; set; }
        public virtual TblEstrategiasIntervencion TblEstrategiasIntervencion { get; set; }
        public virtual TblEvidenciaAprendizaje TblEvidenciaAprendizaje { get; set; }
        public virtual TblInstrumentosEvaluacion TblInstrumentosEvaluacion { get; set; }
        public virtual TblMaterialRecursosDidacticos TblMaterialRecursosDidacticos { get; set; }
        public virtual TblTiempo TblTiempo { get; set; }
        public virtual TblPlaneacion TblPlaneacion { get; set; }
    }
}
